// Generated by CoffeeScript 1.3.3
(function() {
  var Voodoo, fs, p, path, pjson, root, util,
    _this = this;

  util = require('util');

  fs = require('fs');

  p = require('commander');

  path = require('path');

  process.title = "voodoo";

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  pjson = require('../package.json');

  root.version = pjson.version;

  root.Voodoo = Voodoo = (function() {

    function Voodoo(cwd, opts) {
      if ((opts != null) && (opts.base != null)) {
        this.cwd = opts.base.substring(0, 1) === "/" ? opts.base : cwd + '/' + opts.base;
      } else {
        this.cwd = cwd;
      }
      if ((opts != null) && (opts.force != null)) {
        this.force = opts.force;
      } else {
        this.force = false;
      }
      if (this.cwd.substring(this.cwd.length - 1) !== '/') {
        this.cwd += '/';
      }
      this.gruntfile = this.cwd + 'grunt.js';
      if (path.existsSync(this.gruntfile)) {
        console.log('grunt.js exists, nothing generated');
      } else {
        this.generateConfig(this.gruntfile);
      }
      return;
    }

    Voodoo.prototype.generateConfig = function(filepath) {
      var buff;
      if (!path.existsSync(filepath)) {
        buff = fs.readFileSync(__dirname + '/../grunt.js');
        fs.writeFileSync(filepath, buff);
        return console.log('Generated default grunt.js');
      }
    };

    return Voodoo;

  })();

  root.cli = function() {
    p.version(root.version).option('-b, --base <path>', 'working directory for your site (where `assets` folder is in )').option('-v, --verbose', 'verbose output').option('-f, --force', 'a way to force your way past warnings. Want a suggestion? Don\'t use this option, fix your code').parse(process.argv);
    return new Voodoo(process.cwd(), p);
  };

}).call(this);
