// Generated by CoffeeScript 1.3.3

/*
Grunt Task File
---------------

Task: Pulverize
Description:
  Optimizes images in the passed folder (recursive!) using pulverizr
  Expects an object as a param, containing all possible options:

    options: {
      directory: 'assets/img',  // relative from voodoo base path, required
      dry: false,               // dryrun test  
      quiet: false,             // force quiet run
      recursive: false,         // Run recursively
      verbose: false            // Run verbosely
    }

Dependencies: pulverizr
*/


(function() {
  var done, pulverizr,
    _this = this;

  pulverizr = require('pulverizr');

  done = function() {};

  task.registerBasicTask("pulverize", "Squeeze bits from images", function(data, name) {
    done = this.async();
    if (!(data.directory != null)) {
      log.error().error('No directory passed in the options');
      return false;
    }
    task.helper('pulverizr', data);
    if (task.hadErrors() === true) {
      return false;
    }
  });

  task.registerHelper("pulverizr", function(options) {
    log.writeln(options);
    pulverizr.compress(options.directory, options);
    return setTimeout(function() {
      done();
      return log.writeln('Files in "' + options.directory + '" pulverized.');
    }, 1000);
  });

}).call(this);
